version: "3.7"

services:
  bot:
    image: bot
    container_name: bot
    restart: always
    environment:
      PORT: 3000
      SLACK_BOT_TOKEN: $SLACK_BOT_TOKEN
      SLACK_SIGNING_SECRET: $SLACK_SIGNING_SECRET
    ports:
      - 3000:3000

